In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Mayank\Downloads\archive (7)\used_cars_data.csv")
df = df[["Name","Kilometers_Driven","Fuel_Type","Owner_Type","Price"]]
df.head()

,Name,Kilometers_Driven,Fuel_Type,Owner_Type,Price
0,Maruti Wagon R LXI CNG,72000,CNG,First,1.75
1,Hyundai Creta 1.6 CRDi SX Option,41000,Diesel,First,12.50
2,Honda Jazz V,46000,Petrol,First,4.50
3,Maruti Ertiga VDI,87000,Diesel,First,6.00
4,Audi A4 New 2.0 TDI Multitronic,40670,Diesel,Second,17.74

In [25]:
df["Fuel_Type"].value_counts()

Fuel_Type
Diesel      3852
Petrol      3325
CNG           62
LPG           12
Electric       2
Name: count, dtype: int64

# One hot Encoding Using Pandas

In [5]:
pd.get_dummies(df, columns=["Fuel_Type","Owner_Type"])

,Name,Kilometers_Driven,Price,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,Maruti Wagon R LXI CNG,72000,1.75,True,False,False,False,False,True,False,False,False
1,Hyundai Creta 1.6 CRDi SX Option,41000,12.50,False,True,False,False,False,True,False,False,False
2,Honda Jazz V,46000,4.50,False,False,False,False,True,True,False,False,False
3,Maruti Ertiga VDI,87000,6.00,False,True,False,False,False,True,False,False,False
4,Audi A4 New 2.0 TDI Multitronic,40670,17.74,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,89411,NaN,False,True,False,False,False,True,False,False,False
7249,Volkswagen Polo GT TSI,59000,NaN,False,False,False,False,True,True,False,False,False
7250,Nissan Micra Diesel XV,28000,NaN,False,True,False,False,False,True,False,False,False
7251,Volkswagen Polo GT TSI,52262,NaN,False,False,False,False,True,False,False,False,True
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,72443,NaN,False,True,False,False,False,True,False,False,False

In [6]:
pd.get_dummies(df, columns=["Fuel_Type","Owner_Type"],drop_first=True)

,Name,Kilometers_Driven,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,Maruti Wagon R LXI CNG,72000,1.75,False,False,False,False,False,False,False
1,Hyundai Creta 1.6 CRDi SX Option,41000,12.50,True,False,False,False,False,False,False
2,Honda Jazz V,46000,4.50,False,False,False,True,False,False,False
3,Maruti Ertiga VDI,87000,6.00,True,False,False,False,False,False,False
4,Audi A4 New 2.0 TDI Multitronic,40670,17.74,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,89411,NaN,True,False,False,False,False,False,False
7249,Volkswagen Polo GT TSI,59000,NaN,False,False,False,True,False,False,False
7250,Nissan Micra Diesel XV,28000,NaN,True,False,False,False,False,False,False
7251,Volkswagen Polo GT TSI,52262,NaN,False,False,False,True,False,False,True
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,72443,NaN,True,False,False,False,False,False,False

# One Hot Encoding Using SK-Learn

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1],test_size=0.2)

In [17]:
X_train.head()
y_train.head()

7043      NaN
6822      NaN
5486     6.20
4547     4.25
3510    11.45
Name: Price, dtype: float64

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
ohe = OneHotEncoder(drop = "first",sparse_output= False, dtype = np.int32)

In [50]:
X_train_new = ohe.fit_transform(X_train[["Fuel_Type","Owner_Type"]])

In [52]:
X_test_new = ohe.fit_transform(X_test[["Fuel_Type","Owner_Type"]])

In [53]:
X_train_new.shape

(5802, 6)

# Combine Horizontally using Numpy

In [54]:
np.hstack((X_train[["Name","Kilometers_Driven"]].values, X_train_new))

array([['Honda City i-VTEC CVT ZX', 11934, 0, ..., 0, 0, 0],
       ['Hyundai Grand i10 Asta Option', 25000, 0, ..., 0, 0, 0],
       ['Hyundai i20 Active 1.4 SX Dual Tone', 49716, 1, ..., 0, 0, 0],
       ...,
       ['Ford Fiesta 1.4 Duratec EXI', 100000, 0, ..., 0, 0, 0],
       ['Mahindra Scorpio VLX Special Edition BS-IV', 72727, 1, ..., 0,
        1, 0],
       ['Ford Fiesta 1.4 Duratorq ZXI', 68000, 1, ..., 0, 0, 0]],
      dtype=object)

In [55]:
np.hstack((X_train[["Name","Kilometers_Driven"]].values, X_train_new)).shape

(5802, 8)

# OneHotEncoding with Top Categories

In [57]:
counts = df["Name"].value_counts()

In [65]:
df["Name"].nunique()
threshold = 100

In [66]:
repl = counts[counts <= threshold].index

In [68]:
pd.get_dummies(df["Name"].replace(repl,"uncommon")).astype(int)

      uncommon
0            1
1            1
2            1
3            1
4            1
...        ...
7248         1
7249         1
7250         1
7251         1
7252         1

[7253 rows x 1 columns]